#From Open Trivia DB
question_data = [{"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "The flag of South Africa features 7 colours.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "medium",
                  "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Steel is an alloy of Iron and Carbon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The vapor produced by e-cigarettes is actually water.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "&quot;I disapprove of what you say, but I will defend to the death your right to say it&quot; is a quote from French philosopher Voltaire.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Cucumbers are usually more than 90% water.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "Tennis was once known as Racquetball.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "The Olympics tennis court is a giant green screen.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "You could walk from Norway to North Korea while only passing through Russia.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "medium",
                  "question": "During the 2016 United States presidential election, the State of California possessed the most electoral votes, having 55.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In Rocket League, you can play Basketball.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In Portal, the Companion Cube&#039;s ARE sentient.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "medium", "question": "Sugar contains fat.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The movie &quot;Tron&quot; received an Oscar nomination for Best Visual Effects.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In career mode of &quot;Need for Speed: Underground 2&quot;, the first car the player can drive is the BMW M3 GTR.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Art", "type": "boolean", "difficulty": "medium",
                  "question": "Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]